apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-lab
  region: us-east-1

vpc:
  id: 'vpc-0cc0b15b8d103b44c'
  subnets:
    private:
      private-1:
        id: 'subnet-0662b56b19b7dcbdb'
      private-2:
        id: 'subnet-0061e41b45fe6723a'
    public:
      public-1:
        id: 'subnet-0025bcc92730a0629'
      public-2:
        id: 'subnet-00fa48620b0701521'

managedNodeGroups:
  - name: public
    privateNetworking: false
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-0025bcc92730a0629'
    - 'subnet-00fa48620b0701521'
    ssh:
      publicKeyName: eks-node
  - name: private 
    privateNetworking: true
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-0662b56b19b7dcbdb'
    - 'subnet-0061e41b45fe6723a'
    ssh:
      publicKeyName: eks-node
