apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-lab
  region: us-east-1

vpc:
  id: 'vpc-082d701656feacd51'
  subnets:
    private:
      private-1:
        id: 'subnet-08c75ccae88b90838'
      private-2:
        id: 'subnet-05581265734b17c70'
    public:
      public-1:
        id: 'subnet-082f50031b2e44930'
      public-2:
        id: 'subnet-06e8c0cb2ee006b3a'

managedNodeGroups:
  - name: public
    privateNetworking: false
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-082f50031b2e44930'
    - 'subnet-06e8c0cb2ee006b3a'
    ssh:
      publicKeyName: acg0603c
  - name: private 
    privateNetworking: true
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-08c75ccae88b90838'
    - 'subnet-05581265734b17c70'
    ssh:
      publicKeyName: acg0603c
