apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-lab
  region: us-east-1

vpc:
  id: 'vpc-034419acc35c6bbb5'
  subnets:
    private:
      private-1:
        id: 'subnet-0bd5a97f30875a529'
      private-2:
        id: 'subnet-09b62807b05e7ee22'
    public:
      public-1:
        id: 'subnet-0982f0cda58ea4a6f'
      public-2:
        id: 'subnet-06f613624042adf13'

managedNodeGroups:
  - name: public
    privateNetworking: false
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-0982f0cda58ea4a6f'
    - 'subnet-06f613624042adf13'
    ssh:
      publicKeyName: acg0605a
  - name: private 
    privateNetworking: true
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    subnets:
    - 'subnet-0bd5a97f30875a529'
    - 'subnet-09b62807b05e7ee22'
    ssh:
      publicKeyName: acg0605a
